### ISSUE TITLE
Plugin not compatible with version 5.7.0 ?

### ISSUE THREAD

**Issue by fluidscroll** [cgkineo/adapt-pageNav#74]
### Subject of the issue/enhancement/features
Describe your issue here.

When I upload the plugin using the authoring tool, I receive an error stating it's not compatible with my version of Adapt (5.7.0)

### Your environment
* 5.7.0 of the Adapt framework (Authoring tool)
* Chrome - Version 128.0.6613.84 
* Mac OS
* I'm running Adapt locally on Mac via Docker

### Steps to reproduce
Upload the plugin using the authoring tool

### Screenshots (if you can)
<img width="1306" alt="Screenshot 2024-08-25 at 01 40 39" src="https://github.com/user-attachments/assets/0eed09a8-35d5-4ed9-bb48-6b30371d2a4f">

Thanks!

**Comment by swashbuck** [comment]
@fluidscroll The required framework version for plugins can be found in the bower.json or package.json file in the root of the plugin. [Here](https://github.com/cgkineo/adapt-pageNav/blob/master/package.json) is the one for PageNav.

Since you're running Adapt framework 5.7, you'll need to go back a few releases to find a supported version. [2.4.0](https://github.com/cgkineo/adapt-pageNav/releases/tag/v2.4.0) should work for you.
